name: Build Android APK (Debug) - Phone Test

on:
  push:
    branches: [ phone-test-sliders ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Debug APK
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PICOVOICE_ACCESS_KEY: ${{ secrets.PICOVOICE_ACCESS_KEY }}
        run: |
          flutter clean
          flutter build apk --debug \
            --dart-define=OPENAI_API_KEY="$OPENAI_API_KEY" \
            --dart-define=PICOVOICE_ACCESS_KEY="$PICOVOICE_ACCESS_KEY" \
            --dart-define=OPENAI_MODEL="gpt-4o-mini"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: teddy-talks-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk